/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sharkmed;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;

/**
 *
 * @author ASUS
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    
    Border default_border = BorderFactory.createMatteBorder(3,0,0,0,new Color(155,155,155));
    Border blue_border = BorderFactory.createMatteBorder(3,0,0,0,Color.blue);
    
    //create an array of jbuttons
    JButton[] buttons;
    
    public dashboard() {
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null);
        
        //add buttons to the array
        buttons = new JButton[4];
        buttons [0] = home;
        buttons [1] = med;
        buttons [2] = vitamins;
        buttons [3] = supplement;
        
        //default border to the buttons
        for (JButton button : buttons) {
            button.setBorder(default_border);
        }
        
        addAction();
        setButtonBorder(home);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        shark = new javax.swing.JLabel();
        meds = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        supplement = new javax.swing.JButton();
        home = new javax.swing.JButton();
        med = new javax.swing.JButton();
        vitamins = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 234, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(200, 214, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shark.setFont(new java.awt.Font("Leelawadee UI", 1, 35)); // NOI18N
        shark.setForeground(new java.awt.Color(0, 74, 173));
        shark.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shark.setText("shark");
        jPanel2.add(shark, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        meds.setFont(new java.awt.Font("Leelawadee UI", 1, 35)); // NOI18N
        meds.setForeground(new java.awt.Color(0, 109, 255));
        meds.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        meds.setText("meds");
        jPanel2.add(meds, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 90, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/small_logo.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 60, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 80));

        supplement.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        supplement.setForeground(new java.awt.Color(155, 155, 155));
        supplement.setText("Supplements");
        supplement.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        supplement.setContentAreaFilled(false);
        supplement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(supplement, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 90, 30));

        home.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(155, 155, 155));
        home.setText("Home");
        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, 30));

        med.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        med.setForeground(new java.awt.Color(155, 155, 155));
        med.setText("Medicine");
        med.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        med.setContentAreaFilled(false);
        med.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(med, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, 30));

        vitamins.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        vitamins.setForeground(new java.awt.Color(155, 155, 155));
        vitamins.setText("Vitamins");
        vitamins.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vitamins.setContentAreaFilled(false);
        vitamins.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(vitamins, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //create a function to add a mouseClick event to all buttons
    public void addAction(){
        for (JButton button : buttons){
            button.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    setButtonBorder(button);
                }
                @Override
                public void mousePressed(MouseEvent e) {                 
                }
                @Override
                public void mouseReleased(MouseEvent e) {
                    setButtonBorder(button);
                }
                @Override
                public void mouseEntered(MouseEvent e) {
                }
                @Override
                public void mouseExited(MouseEvent e) {
                }
            });
            
        }
        }
    
    //create a function to set border to the selected menu item
    public void setButtonBorder (JButton button){
        
        //reset all buttons to the default border
        for(JButton btn : buttons){
            btn.setBorder(default_border);
        }
        //blue border for the selected item
        button.setBorder(blue_border);
    }
    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        home home = new home();
        home.setVisible(true);
        home.pack();
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       home home = new home();
        home.setVisible(true);
        home.pack();
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton med;
    private javax.swing.JLabel meds;
    private javax.swing.JLabel shark;
    private javax.swing.JButton supplement;
    private javax.swing.JButton vitamins;
    // End of variables declaration//GEN-END:variables
}
