/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sharkmed;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author ASUS
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    
    Border default_border = BorderFactory.createMatteBorder(3,0,0,0,new Color(155,155,155));
    Border blue_border = BorderFactory.createMatteBorder(3,0,0,0,Color.blue);
    
    //create an array of jbuttons
    JButton[] buttons;
    
    public home() {
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null);
        
        //add buttons to the array
        buttons = new JButton[4];
        buttons [0] = home;
        buttons [1] = med;
        buttons [2] = vitamins;
        buttons [3] = supplement;
        
        //default border to the buttons
        for (JButton button : buttons) {
            button.setBorder(default_border);
        }
        
        addAction();
        setButtonBorder(home);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        shark = new javax.swing.JLabel();
        meds = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        supplement = new javax.swing.JButton();
        home = new javax.swing.JButton();
        med = new javax.swing.JButton();
        vitamins = new javax.swing.JButton();
        h_frame1 = new RoundedPanel(50, 187, 203, 221);
        voucher = new RoundedPanel(20,133,161,193);
        off2 = new javax.swing.JLabel();
        promo = new javax.swing.JLabel();
        shopnow = new javax.swing.JLabel();
        celebrate = new javax.swing.JLabel();
        kickoff = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        fireworks = new javax.swing.JLabel();
        sales1 = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(50, 187, 203, 221);
        doc = new javax.swing.JLabel();
        hub = new javax.swing.JLabel();
        health = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 234, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(200, 214, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shark.setFont(new java.awt.Font("Leelawadee UI", 1, 35)); // NOI18N
        shark.setForeground(new java.awt.Color(0, 74, 173));
        shark.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shark.setText("shark");
        jPanel2.add(shark, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        meds.setFont(new java.awt.Font("Leelawadee UI", 1, 35)); // NOI18N
        meds.setForeground(new java.awt.Color(0, 109, 255));
        meds.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        meds.setText("meds");
        jPanel2.add(meds, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 90, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/small_logo.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 60, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 80));

        supplement.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        supplement.setForeground(new java.awt.Color(155, 155, 155));
        supplement.setText("Supplements");
        supplement.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        supplement.setContentAreaFilled(false);
        supplement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplementMouseClicked(evt);
            }
        });
        jPanel1.add(supplement, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 90, 30));

        home.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(155, 155, 155));
        home.setText("Home");
        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, 30));

        med.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        med.setForeground(new java.awt.Color(155, 155, 155));
        med.setText("Medicine");
        med.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        med.setContentAreaFilled(false);
        med.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medMouseClicked(evt);
            }
        });
        med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medActionPerformed(evt);
            }
        });
        jPanel1.add(med, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, 30));

        vitamins.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        vitamins.setForeground(new java.awt.Color(155, 155, 155));
        vitamins.setText("Vitamins");
        vitamins.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vitamins.setContentAreaFilled(false);
        vitamins.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vitamins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vitaminsMouseClicked(evt);
            }
        });
        vitamins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitaminsActionPerformed(evt);
            }
        });
        jPanel1.add(vitamins, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, 30));

        h_frame1.setBackground(new java.awt.Color(228, 234, 241));
        h_frame1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        h_frame1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voucher.setBackground(new java.awt.Color(228, 234, 241));
        voucher.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        voucher.setOpaque(false);
        voucher.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        off2.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        off2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        off2.setText("24% OFF");
        voucher.add(off2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        h_frame1.add(voucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, 40));

        promo.setFont(new java.awt.Font("Leelawadee UI", 0, 8)); // NOI18N
        promo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        promo.setText("Starts from January 1 until March 24, 2024");
        h_frame1.add(promo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 20));

        shopnow.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        shopnow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopnow.setText("SHOP NOW!");
        h_frame1.add(shopnow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, 40));

        celebrate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celebrate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/celebrate.png"))); // NOI18N
        h_frame1.add(celebrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 190, 190));

        kickoff.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 28)); // NOI18N
        kickoff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kickoff.setText("KICK OFF");
        h_frame1.add(kickoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

        year.setFont(new java.awt.Font("Felix Titling", 0, 60)); // NOI18N
        year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year.setText("2024");
        h_frame1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        fireworks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fireworks.png"))); // NOI18N
        h_frame1.add(fireworks, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 340, 240));

        sales1.setFont(new java.awt.Font("Felix Titling", 0, 50)); // NOI18N
        sales1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales1.setText("sales");
        h_frame1.add(sales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jPanel1.add(h_frame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 390, 220));

        jPanel3.setBackground(new java.awt.Color(228, 234, 241));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/doc (1).png"))); // NOI18N
        jPanel3.add(doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, 150));

        hub.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        hub.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hub.setText("HUB");
        jPanel3.add(hub, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        health.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        health.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        health.setText("HEALTH");
        jPanel3.add(health, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 390, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //create a function to add a mouseClick event to all buttons
    public void addAction(){
        for (JButton button : buttons){
            button.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    setButtonBorder(button);
                }
                @Override
                public void mousePressed(MouseEvent e) {                 
                }
                @Override
                public void mouseReleased(MouseEvent e) {
                    setButtonBorder(button);
                }
                @Override
                public void mouseEntered(MouseEvent e) {
                }
                @Override
                public void mouseExited(MouseEvent e) {
                }
            });
            
        }
        }
    
    //create a function to set border to the selected menu item
    public void setButtonBorder (JButton button){
        
        //reset all buttons to the default border
        for(JButton btn : buttons){
            btn.setBorder(default_border);
        }
        //blue border for the selected item
        button.setBorder(blue_border);
    }
    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        home home = new home();
        home.setVisible(true);
        home.pack();
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void medMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medMouseClicked
        // TODO add your handling code here:
        medicine med = new medicine();
        med.setVisible(true);
        med.pack();
        this.dispose();
    }//GEN-LAST:event_medMouseClicked

    private void medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medActionPerformed
        // TODO add your handling code here:
        medicine med = new medicine();
        med.setVisible(true);
        med.pack();
        this.dispose();
    }//GEN-LAST:event_medActionPerformed

    private void vitaminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitaminsActionPerformed
        // TODO add your handling code here:
        vitamins vit = new vitamins();
        vit.setVisible(true);
        vit.pack();
        this.dispose();
    }//GEN-LAST:event_vitaminsActionPerformed

    private void vitaminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vitaminsMouseClicked
        // TODO add your handling code here:
        vitamins vit = new vitamins();
        vit.setVisible(true);
        vit.pack();
        this.dispose();
    }//GEN-LAST:event_vitaminsMouseClicked

    private void supplementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplementMouseClicked
        // TODO add your handling code here:
        supplements sup = new supplements();
        sup.setVisible(true);
        sup.pack();
        this.dispose();
    }//GEN-LAST:event_supplementMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celebrate;
    private javax.swing.JLabel doc;
    private javax.swing.JLabel fireworks;
    private javax.swing.JPanel h_frame1;
    private javax.swing.JLabel health;
    private javax.swing.JButton home;
    private javax.swing.JLabel hub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kickoff;
    private javax.swing.JLabel logo;
    private javax.swing.JButton med;
    private javax.swing.JLabel meds;
    private javax.swing.JLabel off2;
    private javax.swing.JLabel promo;
    private javax.swing.JLabel sales1;
    private javax.swing.JLabel shark;
    private javax.swing.JLabel shopnow;
    private javax.swing.JButton supplement;
    private javax.swing.JButton vitamins;
    private javax.swing.JPanel voucher;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables


public class RoundedPanel extends JPanel {
    private Color backgroundColor;
    private int cornerRadius = 15;

    public RoundedPanel() {
        super();
    }

    public RoundedPanel(int radius, int red, int green, int blue) {
        super();
        cornerRadius = radius;
        backgroundColor = new Color(red, green, blue);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Dimension arcs = new Dimension(cornerRadius, cornerRadius);
        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        if (backgroundColor != null) {
            graphics.setColor(backgroundColor);
        } else {
            graphics.setColor(getBackground());
        }

        graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height);
        graphics.setColor(getForeground());
    }
}

}