/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sharkmed;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class medicine extends javax.swing.JFrame{
    
    private static final String username = "root";
    private static final String password = "02nikk@A";
    private static final String dataConn = "jdbc:mysql://localhost:3306/finals";
      
    Connection sqlCon = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
     
    Border default_border = BorderFactory.createMatteBorder(3,0,0,0,new Color(155,155,155));
    Border blue_border = BorderFactory.createMatteBorder(3,0,0,0,Color.blue);
    
    //create an array of jbuttons
    JButton[] buttons;
    
    public medicine() {
        initComponents();
        
        //center the form
        this.setLocationRelativeTo(null);
               
        //add buttons to the array
        buttons = new JButton[4];
        buttons[0] = home;
        buttons[1] = med;
        buttons[2] = vitamins;
        buttons[3] = supplement;

        
        //default border to the buttons
        //default border to the buttons
        for (JButton button : buttons) {
            button.setBorder(default_border);
        }
        
        addAction();
        setButtonBorder(med); 
        
        // Add ActionListener for the bioADD button
        bioADD.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
    }
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sharkMeds = new javax.swing.JPanel();
        shark = new javax.swing.JLabel();
        meds = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        cart = new javax.swing.JLabel();
        medPanel = new javax.swing.JPanel();
        supplement = new javax.swing.JButton();
        home = new javax.swing.JButton();
        med = new javax.swing.JButton();
        vitamins = new javax.swing.JButton();
        biogesic = new javax.swing.JLabel();
        BiogesicParacetamolTablet1 = new javax.swing.JLabel();
        mg1 = new javax.swing.JLabel();
        mg = new javax.swing.JLabel();
        bioADD = new javax.swing.JButton();
        bio_qv = new javax.swing.JButton();
        medicol = new javax.swing.JLabel();
        medicolAdvance = new javax.swing.JLabel();
        mg2 = new javax.swing.JLabel();
        mg3 = new javax.swing.JLabel();
        mediAdd = new javax.swing.JButton();
        medicol_qv = new javax.swing.JButton();
        medicol1 = new javax.swing.JLabel();
        medicolAdvance1 = new javax.swing.JLabel();
        mg4 = new javax.swing.JLabel();
        mg5 = new javax.swing.JLabel();
        addCart2 = new javax.swing.JButton();
        kremil_qv = new javax.swing.JButton();
        medicol3 = new javax.swing.JLabel();
        medicolAdvance3 = new javax.swing.JLabel();
        mg8 = new javax.swing.JLabel();
        mg9 = new javax.swing.JLabel();
        addCart4 = new javax.swing.JButton();
        mefenamic_qv = new javax.swing.JButton();
        biogesic1 = new javax.swing.JLabel();
        mg10 = new javax.swing.JLabel();
        BiogesicParacetamolTablet2 = new javax.swing.JLabel();
        mg11 = new javax.swing.JLabel();
        addCart5 = new javax.swing.JButton();
        fern_qv = new javax.swing.JButton();
        qtySpinner = new javax.swing.JSpinner();
        qtySpinner1 = new javax.swing.JSpinner();
        addPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTbl = new javax.swing.JTable();
        exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 234, 241));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sharkMeds.setBackground(new java.awt.Color(200, 214, 228));
        sharkMeds.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        sharkMeds.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shark.setFont(new java.awt.Font("Leelawadee UI", 1, 35)); // NOI18N
        shark.setForeground(new java.awt.Color(0, 74, 173));
        shark.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shark.setText("shark");
        sharkMeds.add(shark, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        meds.setFont(new java.awt.Font("Leelawadee UI", 1, 35)); // NOI18N
        meds.setForeground(new java.awt.Color(0, 109, 255));
        meds.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        meds.setText("meds");
        sharkMeds.add(meds, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/small_logo.png"))); // NOI18N
        sharkMeds.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 60, 60));

        cart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart.png"))); // NOI18N
        cart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartMouseClicked(evt);
            }
        });
        sharkMeds.add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 40, 40));

        jPanel1.add(sharkMeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, 80));

        medPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        medPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplement.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        supplement.setForeground(new java.awt.Color(155, 155, 155));
        supplement.setText("Supplements");
        supplement.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        supplement.setContentAreaFilled(false);
        supplement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplementMouseClicked(evt);
            }
        });
        medPanel.add(supplement, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 90, 30));

        home.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(155, 155, 155));
        home.setText("Home");
        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        medPanel.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 30));

        med.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        med.setForeground(new java.awt.Color(155, 155, 155));
        med.setText("Medicine");
        med.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        med.setContentAreaFilled(false);
        med.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medMouseClicked(evt);
            }
        });
        medPanel.add(med, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 30));

        vitamins.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        vitamins.setForeground(new java.awt.Color(155, 155, 155));
        vitamins.setText("Vitamins");
        vitamins.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vitamins.setContentAreaFilled(false);
        vitamins.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vitamins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vitaminsMouseClicked(evt);
            }
        });
        medPanel.add(vitamins, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 30));

        biogesic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biogesic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/biogesic.png"))); // NOI18N
        medPanel.add(biogesic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 90));

        BiogesicParacetamolTablet1.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        BiogesicParacetamolTablet1.setText("Biogesic Paracetamol");
        BiogesicParacetamolTablet1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        medPanel.add(BiogesicParacetamolTablet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 20));

        mg1.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg1.setText("500mg");
        medPanel.add(mg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 20));

        mg.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg.setText("PHP 47.50");
        medPanel.add(mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        bioADD.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        bioADD.setText("Add to cart");
        bioADD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bioADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bioADD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bioADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bioADDMouseClicked(evt);
            }
        });
        bioADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioADDActionPerformed(evt);
            }
        });
        medPanel.add(bioADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 60, 20));

        bio_qv.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        bio_qv.setText("Quick view");
        bio_qv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bio_qv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bio_qv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bio_qv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bio_qvMouseClicked(evt);
            }
        });
        medPanel.add(bio_qv, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 120, 20));

        medicol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medicol.png"))); // NOI18N
        medPanel.add(medicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 90));

        medicolAdvance.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        medicolAdvance.setText("Medicol Advance");
        medicolAdvance.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        medPanel.add(medicolAdvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 20));

        mg2.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg2.setText("400mg");
        medPanel.add(mg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 20));

        mg3.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg3.setText("PHP 252.00");
        medPanel.add(mg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        mediAdd.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mediAdd.setText("Add to cart");
        mediAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mediAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mediAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mediAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediAddActionPerformed(evt);
            }
        });
        medPanel.add(mediAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 60, 20));

        medicol_qv.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        medicol_qv.setText("Quick view");
        medicol_qv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        medicol_qv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medicol_qv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        medicol_qv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicol_qvMouseClicked(evt);
            }
        });
        medicol_qv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicol_qvActionPerformed(evt);
            }
        });
        medPanel.add(medicol_qv, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 120, 20));

        medicol1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/kremil s.png"))); // NOI18N
        medPanel.add(medicol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, 90));

        medicolAdvance1.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        medicolAdvance1.setText("Kremil - S Advance");
        medicolAdvance1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        medPanel.add(medicolAdvance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, 20));

        mg4.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg4.setText("400mg");
        medPanel.add(mg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 20));

        mg5.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg5.setText("PHP 42.50");
        medPanel.add(mg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        addCart2.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        addCart2.setText("Add to cart");
        addCart2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addCart2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCart2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        medPanel.add(addCart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 80, 20));

        kremil_qv.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        kremil_qv.setText("Quick view");
        kremil_qv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kremil_qv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kremil_qv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kremil_qv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kremil_qvMouseClicked(evt);
            }
        });
        kremil_qv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kremil_qvActionPerformed(evt);
            }
        });
        medPanel.add(kremil_qv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 80, 20));

        medicol3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicol3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mefenamic acid.png"))); // NOI18N
        medPanel.add(medicol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 140, 90));

        medicolAdvance3.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        medicolAdvance3.setText("Mefenamic Acid");
        medicolAdvance3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        medPanel.add(medicolAdvance3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, 20));

        mg8.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg8.setText("500mg");
        medPanel.add(mg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, 20));

        mg9.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg9.setText("PHP 31.25");
        medPanel.add(mg9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, -1));

        addCart4.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        addCart4.setText("Add to cart");
        addCart4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addCart4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCart4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        medPanel.add(addCart4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 80, 20));

        mefenamic_qv.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mefenamic_qv.setText("Quick view");
        mefenamic_qv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mefenamic_qv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mefenamic_qv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mefenamic_qv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mefenamic_qvMouseClicked(evt);
            }
        });
        mefenamic_qv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mefenamic_qvActionPerformed(evt);
            }
        });
        medPanel.add(mefenamic_qv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 80, 20));

        biogesic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biogesic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fern c.png"))); // NOI18N
        medPanel.add(biogesic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, 90));

        mg10.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg10.setText("PHP 80.00");
        medPanel.add(mg10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        BiogesicParacetamolTablet2.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        BiogesicParacetamolTablet2.setText("Fern C-Sodium Ascorbate");
        BiogesicParacetamolTablet2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        medPanel.add(BiogesicParacetamolTablet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, 20));

        mg11.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        mg11.setText("568mg");
        medPanel.add(mg11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, 20));

        addCart5.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        addCart5.setText("Add to cart");
        addCart5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addCart5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCart5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        medPanel.add(addCart5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 80, 20));

        fern_qv.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        fern_qv.setText("Quick view");
        fern_qv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fern_qv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fern_qv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fern_qv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fern_qvMouseClicked(evt);
            }
        });
        fern_qv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fern_qvActionPerformed(evt);
            }
        });
        medPanel.add(fern_qv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 80, 20));

        qtySpinner.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        medPanel.add(qtySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 50, 20));

        qtySpinner1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        medPanel.add(qtySpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 50, 20));

        jPanel1.add(medPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 450, 560));

        addPanel.setBackground(new java.awt.Color(102, 102, 102));
        addPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cartTbl);

        addPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 430, -1));

        jPanel1.add(addPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 450, 560));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_red.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //create a function to add a mouseClick event to all buttons
    public void addAction(){
        for (JButton button : buttons){
            button.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    setButtonBorder(button);
                }
                @Override
                public void mousePressed(MouseEvent e) {                 
                }
                @Override
                public void mouseReleased(MouseEvent e) {
                    setButtonBorder(button);
                }
                @Override
                public void mouseEntered(MouseEvent e) {
                }
                @Override
                public void mouseExited(MouseEvent e) {
                }
            });
            
        }
        }
    
    //create a function to set border to the selected menu item
    public void setButtonBorder (JButton button){
        
        //reset all buttons to the default border
        for(JButton btn : buttons){
            btn.setBorder(default_border);
        }
        //blue border for the selected item
        button.setBorder(blue_border);
    }
    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        home home = new home();
        home.setVisible(true);
        home.pack();
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void vitaminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vitaminsMouseClicked
        // TODO add your handling code here:
        vitamins vit = new vitamins();
        vit.setVisible(true);
        vit.pack();
        this.dispose();
    }//GEN-LAST:event_vitaminsMouseClicked

    private void medMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medMouseClicked
        // TODO add your handling code here:
        medicine med = new medicine();
        med.setVisible(true);
        med.pack();
        this.dispose();
    }//GEN-LAST:event_medMouseClicked

    private void supplementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplementMouseClicked
        // TODO add your handling code here:
        supplements sup = new supplements();
        sup.setVisible(true);
        sup.pack();
        this.dispose();
    }//GEN-LAST:event_supplementMouseClicked

    private void bio_qvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bio_qvMouseClicked
        // TODO add your handling code here:
    
    ImageIcon bio = new ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Finals\\medsImage\\biogesic.png");

    JOptionPane.showMessageDialog(
        null,
        "Biogesic is a medication that is typically used to relieve mild to moderate pain such as"
            + "\nheadache, backache, menstrual cramps, muscular strain, minor arthritis pain,"
            + "\ntoothache, and reduce fevers caused by illnesses such as the common cold and flu.",
        "BIOGESIC",
        JOptionPane.INFORMATION_MESSAGE,
        bio
    );
    }//GEN-LAST:event_bio_qvMouseClicked

    private void medicol_qvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicol_qvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_medicol_qvMouseClicked

    private void kremil_qvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kremil_qvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kremil_qvMouseClicked

    private void fern_qvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fern_qvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fern_qvMouseClicked

    private void mefenamic_qvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mefenamic_qvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mefenamic_qvMouseClicked

    private void medicol_qvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicol_qvActionPerformed
        ImageIcon bio = new ImageIcon("medicol.png");
        JOptionPane.showMessageDialog(null,"Relief of headache including migraine, neuralgia; toothache, muscular aches, minor arthritic pain, backache,"
                + "\n minor aches & pains associated w/ common cold & menstrual cramps (dysmenorrhea). Reduction of fever."
                + "\ntoothache, and reduce fevers caused by illnesses such as the common cold and flu."
                ,"medicol",JOptionPane.INFORMATION_MESSAGE,bio);
    }//GEN-LAST:event_medicol_qvActionPerformed

    private void kremil_qvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kremil_qvActionPerformed
        ImageIcon bio = new ImageIcon("kremil s.png");
        JOptionPane.showMessageDialog(null,"For moderate to severe hyperacidity and heartburn"
                ,"kremil s",JOptionPane.INFORMATION_MESSAGE,bio);
    }//GEN-LAST:event_kremil_qvActionPerformed

    private void fern_qvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fern_qvActionPerformed
         ImageIcon bio = new ImageIcon("fern c.png");
        JOptionPane.showMessageDialog(null,"* Stronger immune system boosting powers.\n" +
"* Rich in powerful Antioxidants."
                ,"fern c",JOptionPane.INFORMATION_MESSAGE,bio);
    }//GEN-LAST:event_fern_qvActionPerformed

    private void mefenamic_qvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mefenamic_qvActionPerformed
         ImageIcon bio = new ImageIcon("mefenamic acid.png");
        JOptionPane.showMessageDialog(null,"used to treat mild to moderate pain. It may also be used to treat menstrual cramps and other conditions as determined by your doctor."
                ,"mefenamic acid",JOptionPane.INFORMATION_MESSAGE,bio);
    }//GEN-LAST:event_mefenamic_qvActionPerformed

    private void cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseClicked
        addToCart a = new addToCart();
        a.setVisible(true);
        a.pack();
        this.dispose();
    }//GEN-LAST:event_cartMouseClicked

    private void bioADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioADDMouseClicked
        addToCart a = new addToCart();
        a.setVisible(true);
        a.pack();
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlCon = DriverManager.getConnection(dataConn, username, password);
        
        // Assuming you have a JSpinner named qtySpinner in your addToCart frame
        int quantity = (int) qtySpinner1.getValue();

        String query = "SELECT * FROM finals WHERE id = '1'";
        pst = sqlCon.prepareStatement(query);
        rs = pst.executeQuery();

        StringBuilder message = new StringBuilder("Data from the database:\n\n");
        while (rs.next()) {
            int itemId = rs.getInt("id");
            String name = rs.getString("Name");
            String price = rs.getString("Price");
            int stocks = rs.getInt("Stocks");

            // Check if there are enough stocks
            if (stocks >= quantity) {
                message.append(name).append(": ").append(price).append("\n");

                // Insert the data into the addToCart table
                int i = Integer.valueOf(quantity);
                
                a.BiogesicParacetamolTablet1.setText(String.valueOf(i));
        
                a.addtables(1, "Biogesic Paracetamol", i, 47.5);
                SwingUtilities.invokeLater(() -> a.cal());    
                a.cal();
                
                
                // Update the stocks in the finals table
                String updateStocksQuery = "UPDATE finals SET Stocks = Stocks - ? WHERE id = ?";
                try (PreparedStatement updateStocksPst = sqlCon.prepareStatement(updateStocksQuery)) {
                    updateStocksPst.setInt(1, quantity);
                    updateStocksPst.setInt(2, itemId);
                    updateStocksPst.executeUpdate();
                    
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            } else {
                message.append("Not enough stocks for ").append(name).append("\n");               
            }
        }
        JOptionPane.showMessageDialog(
                null,
                message.toString(),
                "Database Data",
                JOptionPane.INFORMATION_MESSAGE);
    } catch (ClassNotFoundException | SQLException ex) {
        ex.printStackTrace();
    } finally {
        // Close resources
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (sqlCon != null) sqlCon.close();
        } catch (SQLException e) {           
            e.printStackTrace();
            }
        // Make the cart table visible in addToCart
        a.cartTbl.setVisible(true);
        // Close the current instance of the medicine frame
        this.dispose();
        }
        
    }//GEN-LAST:event_bioADDMouseClicked

    private void bioADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioADDActionPerformed

    }//GEN-LAST:event_bioADDActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void mediAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediAddActionPerformed
        addToCart a = new addToCart();
        a.setVisible(true);
        a.pack();
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlCon = DriverManager.getConnection(dataConn, username, password);
        
        // Assuming you have a JSpinner named qtySpinner in your addToCart frame
        int quantity = (int) qtySpinner.getValue();

        String query = "SELECT * FROM finals WHERE id = '2'";
        pst = sqlCon.prepareStatement(query);
        rs = pst.executeQuery();

        StringBuilder message = new StringBuilder("Data from the database:\n\n");
        while (rs.next()) {
            int itemId = rs.getInt("id");
            String name = rs.getString("Name");
            String price = rs.getString("Price");
            int stocks = rs.getInt("Stocks");

            // Check if there are enough stocks
            if (stocks >= quantity) {
                message.append(name).append(": ").append(price).append("\n");

                // Insert the data into the addToCart table
                int i = Integer.valueOf(quantity);
                
                a.medicolAdvance.setText(String.valueOf(i));
        
                a.addtables(2, "Medicol Advance", i, 252.00);
                SwingUtilities.invokeLater(() -> a.cal());    
                a.cal();
                System.out.println(i);
                
                // Update the stocks in the finals table
                String updateStocksQuery = "UPDATE finals SET Stocks = Stocks - ? WHERE id = ?";
                try (PreparedStatement updateStocksPst = sqlCon.prepareStatement(updateStocksQuery)) {
                    updateStocksPst.setInt(1, quantity);
                    updateStocksPst.setInt(2, itemId);
                    updateStocksPst.executeUpdate();
                    
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            } else {
                message.append("Not enough stocks for ").append(name).append("\n");               
            }
        }
        JOptionPane.showMessageDialog(
                null,
                message.toString(),
                "Database Data",
                JOptionPane.INFORMATION_MESSAGE);
    } catch (ClassNotFoundException | SQLException ex) {
        ex.printStackTrace();
    } finally {
        // Close resources
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (sqlCon != null) sqlCon.close();
        } catch (SQLException e) {           
            e.printStackTrace();
            }
        // Make the cart table visible in addToCart
        a.cartTbl.setVisible(true);
        // Close the current instance of the medicine frame
        this.dispose();
        }
    }//GEN-LAST:event_mediAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicine().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BiogesicParacetamolTablet1;
    private javax.swing.JLabel BiogesicParacetamolTablet2;
    private javax.swing.JButton addCart2;
    private javax.swing.JButton addCart4;
    private javax.swing.JButton addCart5;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton bioADD;
    private javax.swing.JButton bio_qv;
    private javax.swing.JLabel biogesic;
    private javax.swing.JLabel biogesic1;
    private javax.swing.JLabel cart;
    private javax.swing.JTable cartTbl;
    private javax.swing.JLabel exit;
    private javax.swing.JButton fern_qv;
    private javax.swing.JButton home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kremil_qv;
    private javax.swing.JLabel logo;
    private javax.swing.JButton med;
    private javax.swing.JPanel medPanel;
    private javax.swing.JButton mediAdd;
    private javax.swing.JLabel medicol;
    private javax.swing.JLabel medicol1;
    private javax.swing.JLabel medicol3;
    private javax.swing.JLabel medicolAdvance;
    private javax.swing.JLabel medicolAdvance1;
    private javax.swing.JLabel medicolAdvance3;
    private javax.swing.JButton medicol_qv;
    private javax.swing.JLabel meds;
    private javax.swing.JButton mefenamic_qv;
    private javax.swing.JLabel mg;
    private javax.swing.JLabel mg1;
    private javax.swing.JLabel mg10;
    private javax.swing.JLabel mg11;
    private javax.swing.JLabel mg2;
    private javax.swing.JLabel mg3;
    private javax.swing.JLabel mg4;
    private javax.swing.JLabel mg5;
    private javax.swing.JLabel mg8;
    private javax.swing.JLabel mg9;
    private javax.swing.JSpinner qtySpinner;
    private javax.swing.JSpinner qtySpinner1;
    private javax.swing.JLabel shark;
    private javax.swing.JPanel sharkMeds;
    private javax.swing.JButton supplement;
    private javax.swing.JButton vitamins;
    // End of variables declaration//GEN-END:variables


public class RoundedPanel extends JPanel {
    private Color backgroundColor;
    private int cornerRadius = 15;

    public RoundedPanel() {
        super();
    }

    public RoundedPanel(int radius, int red, int green, int blue) {
        super();
        cornerRadius = radius;
        backgroundColor = new Color(red, green, blue);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Dimension arcs = new Dimension(cornerRadius, cornerRadius);
        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        if (backgroundColor != null) {
            graphics.setColor(backgroundColor);
        } else {
            graphics.setColor(getBackground());
        }

        graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height);
        graphics.setColor(getForeground());
    }
}

}
